### ISSUE TITLE
unable to get floating definition for French and German

### ISSUE THREAD

**Issue by mkeroppi** [pnlpal/dictionaries#30]
Can confirm that English, Spanish, and Italian work.

**Comment by revir** [comment]
I want to know how many people have this problem. Because French and German both work for me. 

![image](https://user-images.githubusercontent.com/3252034/99049052-53d82980-25d1-11eb-8e07-0f0cc22f701b.png)

![image](https://user-images.githubusercontent.com/3252034/99049221-8f72f380-25d1-11eb-91d9-c53c131f5e69.png)

**Comment by mkeroppi** [comment]
I'm able to get definitions for some words in French and German now (less for French) - not sure what happened.

**Comment by revir** [comment]
@mkeroppi you are right, I also found this problem. And have already got the solution. New version will be released in one  or two days.

**Comment by revir** [comment]
@mkeroppi  With v2.4.0 update, both French and German are improved now. Please have a look and tell me what do you think.

Notice: chrome version is still under review, I guess it will need a couple of days. Firefox and crx file are ready now.

**Comment by revir** [comment]
No further feedback, I consider it's resolved. Thanks.
